# Generated by Django 4.2.6 on 2023-11-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='segmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='evento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('V', 'Vacaciones'), ('F', 'Feriado'), ('SA', 'Suspensión de actividades'), ('SAP', 'Suspension de actividades pm'), ('PL', 'Periodo Lectivo'), ('SE', 'Suspensión de evaluaciones'), ('C', 'Ceremonia'), ('E', 'EDDA'), ('EV', 'Evaluacion'), ('Ay', 'Ayudantias'), ('HA', 'Hito académico'), ('SeA', 'Secretaria académica'), ('OAI', 'OAI')], max_length=100)),
                ('segmento', models.ManyToManyField(to='rest.segmento')),
            ],
        ),
    ]
