# Generated by Django 4.2.7 on 2023-11-28 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='segmento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserSegmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.segmento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='evento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('V', 'Vacaciones'), ('F', 'Feriado'), ('SA', 'Suspensión de actividades'), ('SAP', 'Suspension de actividades pm'), ('PL', 'Periodo Lectivo'), ('SE', 'Suspensión de evaluaciones'), ('C', 'Ceremonia'), ('E', 'EDDA'), ('EV', 'Evaluacion'), ('Ay', 'Ayudantias'), ('HA', 'Hito académico'), ('SeA', 'Secretaria académica'), ('OAI', 'OAI')], max_length=100)),
                ('segmento', models.ManyToManyField(to='rest.segmento')),
            ],
        ),
    ]
